---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(levelname)s - %(name)s - %(message)s"

handlers:
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: simple
        filename: cameraSurveillance.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: WARNING
    handlers: [error_file_handler]
...
